name: Terraform Destroy

on:
  push:
    branches: [deployment]

jobs:

#   monitor:
#     if: startsWith(github.event.head_commit.message, 'destroy')
#     runs-on: ubuntu-latest
#     # defaults:
#     #   run:
#     #     working-directory: k8s

    
      

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v2

#     - name: Setup kubectl
#       uses: azure/setup-kubectl@v3
#       with:
#         version: "v1.33.0"

#     - name: Configure AWS credentials
#       uses: aws-actions/configure-aws-credentials@v1
#       with:
#         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#         aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

#     - name: Update kubeconfig
#       run: aws eks update-kubeconfig --name hr-stag-eksdemo1 --region ${{ secrets.AWS_DEFAULT_REGION }}


#     - name: Delete helm clusters
#       run: |
#         helm uninstall stable -n prometheus
#         helm uninstall my-helm-app
#         helm uninstall aws-load-balancer-controller -n kube-system

  terraform:
    if: startsWith(github.event.head_commit.message, 'destroy')
    runs-on: ubuntu-latest
    # needs: 
    #   - monitor
    defaults:
      run:
        working-directory: Terraform

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.4.6

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Terraform Init & Destroy
      run: |
        terraform init
        terraform destroy --auto-approve
        